/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Book
 */
export interface Book {
    /**
     * 
     * @type {any}
     * @memberof Book
     */
    isbn10: any | null;
    /**
     * 
     * @type {any}
     * @memberof Book
     */
    name: any | null;
    /**
     * 
     * @type {any}
     * @memberof Book
     */
    unitYen: any | null;
    /**
     * 
     * @type {any}
     * @memberof Book
     */
    imageSrc: any | null;
}

/**
 * Check if a given object implements the Book interface.
 */
export function instanceOfBook(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isbn10" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "unitYen" in value;
    isInstance = isInstance && "imageSrc" in value;

    return isInstance;
}

export function BookFromJSON(json: any): Book {
    return BookFromJSONTyped(json, false);
}

export function BookFromJSONTyped(json: any, ignoreDiscriminator: boolean): Book {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isbn10': json['isbn_10'],
        'name': json['name'],
        'unitYen': json['unit_yen'],
        'imageSrc': json['image_src'],
    };
}

export function BookToJSON(value?: Book | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'isbn_10': value.isbn10,
        'name': value.name,
        'unit_yen': value.unitYen,
        'image_src': value.imageSrc,
    };
}

