/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookListResponse
 */
export interface BookListResponse {
    /**
     * 
     * @type {any}
     * @memberof BookListResponse
     */
    books: any | null;
}

/**
 * Check if a given object implements the BookListResponse interface.
 */
export function instanceOfBookListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "books" in value;

    return isInstance;
}

export function BookListResponseFromJSON(json: any): BookListResponse {
    return BookListResponseFromJSONTyped(json, false);
}

export function BookListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'books': json['books'],
    };
}

export function BookListResponseToJSON(value?: BookListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'books': value.books,
    };
}

