FROM node:18.17.0-alpine as builder
WORKDIR /app

COPY ./frontend/ /app
RUN yarn build

FROM nginx as production
WORKDIR /app
COPY ./web/nginx/conf.d /etc/nginx/conf.d
COPY --from=builder /app/dist/ /usr/share/nginx/html
