version: "3"
services:
    web:
        build:
            context: ./
            dockerfile: Containerfile.web
        ports:
            - "8080:80"
        volumes:
            - ./web/nginx/conf.d/default_local.conf:/etc/nginx/conf.d/default.conf
            - ./frontend/dist:/usr/share/nginx/html
    api:
        build:
            context: ./
            dockerfile: Containerfile.api
        volumes:
            - ./api:/app/api
            - ~/.aws:/root/.aws
        ports:
            - "8000:8000"
        working_dir: /app/api
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
        env_file:
            - .env
        environment:
            - OTLP_EXPLORTER_ENDPOINT=udp://otel-collector:4317
            - OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST="".*""
            - OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_RESPONSE=".*"
            - OTEL_PYTHON_EXCLUDED_URLS="ping"
            - OTEL_SERVICE_NAME=playground-dev
    otel-collector:
        build:
            context: ./
            dockerfile: Containerfile.otel
        volumes:
            - ./otel/otel-config.yaml:/etc/otel-agent-config.yaml
            - ~/.aws:/root/.aws
        ports:
            - 4317:4317
volumes:
    db-data:
