version: "3"
services:
    web:
        container_name: web
        image: nginx:alpine
        depends_on:
            - api
        ports:
            - "8080:80"
        volumes:
            - ./web/nginx/conf.d:/etc/nginx/conf.d
    api:
        build:
            context: ./
            dockerfile: Containerfile.api
        volumes:
            - ./api:/app/api
        ports:
            - "8000:8000"
        working_dir: /app/api
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
    db-data:
