receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch/traces:
    timeout: 5s
    send_batch_size: 50

exporters:
  awsxray:
    region: "ap-northeast-1"

service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - awsxray
