name: lint and test

on:
  push:
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Containerfile.local
          tags: ${{ github.repository }}:${{ github.ref_name }}
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
